# Generated by Django 5.2 on 2025-06-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
