# Generated by Django 5.2 on 2025-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_artwork_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='artwork',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
