# Generated by Django 5.2 on 2025-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_alter_artwork_options_artwork_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
