# Generated by Django 5.0.6 on 2024-08-19 23:21

import blog.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='what are you looking for?')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city or neighborhood')),
                ('description', models.TextField(default='', max_length=400, verbose_name='description')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('social_link', models.URLField(blank=True, null=True, verbose_name='social')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image1')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image5')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image6')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.get_image_filename, verbose_name='Image')),
                ('personal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.personal')),
            ],
        ),
    ]
