# Generated by Django 5.0.6 on 2024-08-27 03:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name="What's your problem?")),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city or neighborhood')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='content')),
                ('contact', models.TextField(blank=True, null=True, verbose_name='contact info')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
