# Generated by Django 5.0.6 on 2024-08-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='image6',
        ),
    ]
