# Generated by Django 5.0.6 on 2024-08-26 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
