# Generated by Django 5.0.6 on 2024-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_name',
            field=models.CharField(default='', max_length=100, verbose_name='Display Name'),
            preserve_default=False,
        ),
    ]
