# Generated by Django 5.0.6 on 2024-08-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_personal_post_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='social_link',
        ),
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='contact info'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name="What's your problem?"),
        ),
    ]
