# Generated by Django 5.0.6 on 2024-10-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Display Name'),
        ),
    ]
