# Generated by Django 5.0.6 on 2024-08-20 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_description_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anon_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
