# Generated by Django 5.0.6 on 2024-11-11 20:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[blog.models.validate_media_file]),
        ),
    ]
