# Generated by Django 5.0.6 on 2024-08-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=400, verbose_name='description'),
        ),
    ]
