# Generated by Django 5.1.3 on 2024-11-22 23:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_media_file_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[blog.models.validate_media_file, blog.models.validate_video_file_size], verbose_name='Image or video (<10 MB)'),
        ),
    ]
