# Generated by Django 5.0.6 on 2024-08-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='description'),
        ),
    ]
