# Generated by Django 5.0.6 on 2024-08-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_description_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
