# Generated by Django 4.2.17 on 2024-12-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='end_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
