# Generated by Django 4.2.17 on 2024-12-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
