# Generated by Django 4.2.17 on 2025-01-06 02:00

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='media/', validators=[blog.models.validate_media_file, blog.models.validate_video_file_size], verbose_name='Image or video (<50 MB)'),
        ),
    ]
