# Generated by Django 4.2.17 on 2025-01-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_ip_address_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat_session', models.UUIDField(editable=False)),
                ('sender_id', models.UUIDField(editable=False)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('message', 'Message'), ('status', 'Status'), ('matched', 'Matched'), ('disconnected', 'Disconnected')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['chat_session'], name='blog_chatme_chat_se_e03f50_idx'), models.Index(fields=['sender_id'], name='blog_chatme_sender__a48d0e_idx')],
            },
        ),
    ]
