# Generated by Django 4.2.17 on 2025-01-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_comment_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_session',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
