# Generated by Django 4.2.17 on 2025-02-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_chatmessage_chat_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquerylog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='encrypted_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='encrypted_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='encrypted_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='encrypted_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
