# Generated by Django 4.2.17 on 2025-02-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_searchquerylog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
