# Generated by Django 4.2.17 on 2025-02-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_searchquerylog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
