# Generated by Django 4.2.17 on 2025-02-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_post_is_image_post_is_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='ip_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
