# Generated by Django 4.2.19 on 2025-04-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_encrypt_existing_ips_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='encrypted_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
