# Generated by Django 4.2.19 on 2025-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_encrypt_existing_ips_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpost',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='spam_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='spam_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='spam_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='spam_score',
            field=models.IntegerField(default=0),
        ),
    ]
