# Generated by Django 4.2.19 on 2025-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_testpost_content_comment_spam_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_potentially_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_potentially_spam',
            field=models.BooleanField(default=False),
        ),
    ]
