# Generated by Django 4.2.17 on 2025-09-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_comment_is_potentially_spam_post_is_potentially_spam'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_on'], name='blog_commen_created_ea9152_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_on'], name='blog_commen_post_id_91c148_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['spam_score', '-created_on'], name='blog_commen_spam_sc_07851a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment'], name='blog_commen_parent__abea19_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['spam_score', '-date_posted'], name='blog_post_spam_sc_fb8546_idx'),
        ),
    ]
