# Generated by Django 4.2.17 on 2025-09-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_add_comment_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='excerpt',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='formatted_date',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='formatted_date',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
