# Generated by Django 4.2.19 on 2025-09-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_comment_excerpt_comment_formatted_date_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
