# Generated by Django 4.2.19 on 2025-09-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_comment_reviewed_post_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='restored',
            field=models.BooleanField(default=False),
        ),
    ]
