# Generated by Django 4.2.17 on 2025-09-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_comment_restored_post_restored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='restored',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='restored',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
