# Generated by Django 4.2.17 on 2025-09-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_aichatsession_sitenotification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['session_id'], name='ai_chat_ses_session_8767e9_idx'),
        ),
        migrations.AlterModelTable(
            name='aichatsession',
            table='ai_chat_sessions',
        ),
    ]
