# Generated by Django 4.2.17 on 2025-09-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_aichatsession_ai_chat_ses_session_8767e9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_chats', to='blog.aichatsession')),
            ],
            options={
                'db_table': 'shared_chats',
                'indexes': [models.Index(fields=['share_id'], name='shared_chat_share_i_587ae0_idx'), models.Index(fields=['-created_at'], name='shared_chat_created_b72376_idx')],
            },
        ),
    ]
