# Generated by Django 4.2.17 on 2025-09-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_sharedchat'),
    ]

    operations = [
    ]
