# Generated by Django 4.2.17 on 2025-09-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20250927_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedchat',
            name='chat_session',
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='share_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['share_id'], name='ai_chat_ses_share_i_5e6521_idx'),
        ),
        migrations.DeleteModel(
            name='SharedChat',
        ),
    ]
