# Generated by Django 4.2.17 on 2025-09-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_make_share_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenotification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitenotification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitenotification',
            name='notification_type',
            field=models.CharField(choices=[('modal', 'Modal'), ('floating', 'Floating'), ('banner', 'Banner')], default='floating', max_length=10),
        ),
        migrations.AddField(
            model_name='sitenotification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('chat', 'Chat'), ('feature', 'Feature')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='sitenotification',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='sitenotification',
            index=models.Index(fields=['priority'], name='site_notifi_priorit_2ccb97_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenotification',
            index=models.Index(fields=['is_active'], name='site_notifi_is_acti_129067_idx'),
        ),
    ]
