# Generated by Django 4.2.17 on 2025-10-02 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_sitenotification_expires_at_and_more'),
    ]

    operations = [
    ]
