# Generated by Django 4.2.17 on 2025-10-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_add_missing_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['date_blocked'], name='blocked_ips_date_bl_3015d4_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['is_permanent'], name='blocked_ips_is_perm_f80ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['expires'], name='blocked_ips_expires_becb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['is_permanent', 'expires'], name='blocked_ips_is_perm_668d93_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['name'], name='blog_commen_name_b274f8_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_potentially_spam', '-created_on'], name='blog_commen_is_pote_ad0e61_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['-created_at'], name='blog_list_created_1d6c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['ip_address'], name='blog_list_ip_addr_377b35_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['display_name'], name='blog_post_display_a3df3a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-date_posted'], name='blog_post_author__8b4c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['parent_post'], name='blog_post_parent__688e58_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_potentially_spam', '-date_posted'], name='blog_post_is_pote_6b58cd_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['-timestamp'], name='blog_search_timesta_5f0ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['query'], name='blog_search_query_6b5a73_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['user', '-timestamp'], name='blog_search_user_id_5e2bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['-timestamp'], name='blog_summar_timesta_770150_idx'),
        ),
    ]
